### ISSUE TITLE
Restart resource after getting job

### ISSUE THREAD

**Issue by M3Owner2006** [yunglean4171/ylean_gruppe6job#1]
After getting the job at the job center/ city hall, you have to restart the resource in order to start a job, this is an issue because if someone else is in the middle of a run they will not receive their money at the end of the job.

**Comment by yunglean4171** [comment]
> After getting the job at the job center/ city hall, you have to restart the resource in order to start a job, this is an issue because if someone else is in the middle of a run they will not receive their money at the end of the job.

esx or qbcore?

**Comment by Moenesb132** [comment]
QBCORE

**Comment by yunglean4171** [comment]
its fixed for both versions
